name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  ci:
    name: CD
    uses: nu12/templates/.github/workflows/go-release.yml@main
    with:
      go-binary-name: 'template-go'
      go-main: 'main.go greeting.go'
      go-version: '1.22.5'
      release-linux-amd64: true
      release-win-amd64: true
      release-darwin-amd64: true
      release-darwin-arm64: true
      release-docker: true
      version: '${{ github.ref_name }}'
    secrets: inherit
