name: 'Continuous Integration'

on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  ci:
    uses: nu12/templates/.github/workflows/go-pr.yml@main
    with:
      run-lint: true
      run-test: true
      run-docker-build: true
      go-version: '1.22.5'
      docker-tag: 'latest'
    secrets: inherit
