on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: nu12/templates/actions/test/go@main
        with:
          go-version: '1.22.5'